### ISSUE TITLE
only zeros published on /gx5/nav/heading when use_enu_frame=true

### ISSUE THREAD

**Issue by YairBarzilayBWR** [LORD-MicroStrain/microstrain_inertial_driver_common#21]
Hi,

When setting use_enu_frame to true the heading in the topic /gx5/nav/heading is constantly zero.

Maybe this is on purpose because heading is usually wrt north (?) but if not, its missing.

-Yair

**Comment by nathanmillerparker** [comment]
Hi Yair,

Just committed a fix for this.  Please let me know if you have any other issues.

Nathan

**Comment by YairBarzilayBWR** [comment]
@nathanmillerparker awesome thank you. can you please advance the submodule commits from within the microstrain_inertial_driver, or create a latest release? submodule "common" currently points to [32af4d9](https://github.com/LORD-MicroStrain/microstrain_inertial_driver_common/tree/32af4d925d12d50ff16621d16a4b6ff136bb0495) so we cannot download the zip version and if we clone the microstrain_inertial_driver repo we need to manually checkout main and pull in the the "common" submodule which then always shows up as a change to be commited from our outer repo.

**Comment by YairBarzilayBWR** [comment]
btw I tested the heading and the values dont seem right:
"""
heading_deg: 4671.82861328
heading_rad: 81.5387878418
status_flags: 0
"""

**Comment by nathanmillerparker** [comment]
Hi Yair,

Sorry about that.... I've fixed this and it is awaiting Rob's review.  This should have never happened as I tested the fix prior to commit, but must have undone my last change before the commit (changing from degrees to radians in part of the calculation.) 

We will also get the submodule commits worked out.  I'll let you know when it's done.

**Comment by robbiefish** [comment]
Hi @YairBarzilayBWR,

The following PRs will update the submodules for the parent repo:

LORD-MicroStrain/microstrain_inertial#150
LORD-MicroStrain/microstrain_inertial#151

We will be making a release soon, but there are a few other things I would like to get in before making a release. It will probably be released to the ROS package index this Friday if that is important to you.

**Comment by YairBarzilayBWR** [comment]
Hi @nathanmillerparker and @robbiefish 
Thanks for your responses!
I'm still having issues with the setup.

I tried downloading the release and compiling, i could be missing something but the release seems to only contain ros_mscl, no microstrain_inertial_driver and all of its sub modules.

downloading the repo as a zip is also an issue becuase the submodules are missing. So the only option left is to clone recursive, which is the least favourable option for us.

For now i got it working. ill be testing the heading again and will let you know in case i find any other issues.

Thanks!

**Comment by YairBarzilayBWR** [comment]
Heading seems to be working as intended, closing the issue. Thank you...
